package vista;

/**
 *
 * @author Elias
 */
public class LoginWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginWindow.class.getName());

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginWindow = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        signInText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        mailInput = new javax.swing.JTextField();
        passwordText = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        frgPasswordButton = new javax.swing.JButton();
        rememberUserButton = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        orText = new javax.swing.JLabel();
        signWithText = new javax.swing.JLabel();
        signGoogleButton = new javax.swing.JButton();
        signFacebookButton = new javax.swing.JButton();
        signUpButton = new javax.swing.JButton();
        noAccText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 960));
        setMinimumSize(new java.awt.Dimension(540, 960));
        setPreferredSize(new java.awt.Dimension(540, 960));

        titleText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("By Me Too!");

        signInText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        signInText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInText.setText("Sign In");

        emailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailText.setText("Email");

        mailInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mailInput.setText("segaega666@gmail.com");

        passwordText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordText.setText("Password");

        passwordInput.setText("jPasswordField1");

        frgPasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frgPasswordButton.setForeground(new java.awt.Color(102, 102, 102));
        frgPasswordButton.setText("Forgot Password?");

        rememberUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rememberUserButton.setText("Remember me");

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Login");

        orText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        orText.setForeground(new java.awt.Color(153, 153, 153));
        orText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orText.setText("-OR-");

        signWithText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signWithText.setForeground(new java.awt.Color(102, 102, 102));
        signWithText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signWithText.setText("Sign it with");

        signGoogleButton.setText("Google");

        signFacebookButton.setText("Facebook");

        signUpButton.setText("Sign Up!");
        signUpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        noAccText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noAccText.setText("Dont hace account yet?");

        javax.swing.GroupLayout loginWindowLayout = new javax.swing.GroupLayout(loginWindow);
        loginWindow.setLayout(loginWindowLayout);
        loginWindowLayout.setHorizontalGroup(
            loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordText)
                    .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginWindowLayout.createSequentialGroup()
                        .addComponent(rememberUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(frgPasswordButton))
                    .addComponent(passwordInput)
                    .addComponent(mailInput)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginWindowLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(signGoogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(signFacebookButton)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(loginWindowLayout.createSequentialGroup()
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signInText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signWithText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(loginWindowLayout.createSequentialGroup()
                                .addComponent(noAccText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(signUpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        loginWindowLayout.setVerticalGroup(
            loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signInText)
                .addGap(47, 47, 47)
                .addComponent(emailText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rememberUserButton)
                    .addComponent(frgPasswordButton))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signWithText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signGoogleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signFacebookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(loginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noAccText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailText;
    private javax.swing.JButton frgPasswordButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginWindow;
    private javax.swing.JTextField mailInput;
    private javax.swing.JLabel noAccText;
    private javax.swing.JLabel orText;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordText;
    private javax.swing.JCheckBox rememberUserButton;
    private javax.swing.JButton signFacebookButton;
    private javax.swing.JButton signGoogleButton;
    private javax.swing.JLabel signInText;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel signWithText;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
