package vista;

/**
 *
 * @author Elias
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindowPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        favoriteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        navBar = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        whatToBuyWindowButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        addProductsWindowButton = new javax.swing.JButton();
        productTemplatePanel = new javax.swing.JPanel();
        productTitle = new javax.swing.JLabel();
        Image = new javax.swing.JPanel();
        productTag = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        productTemplatePanel1 = new javax.swing.JPanel();
        productTitle1 = new javax.swing.JLabel();
        productImage1 = new javax.swing.JPanel();
        productTag1 = new javax.swing.JLabel();
        productPrice1 = new javax.swing.JLabel();
        addProductButton1 = new javax.swing.JButton();
        productTemplatePanel2 = new javax.swing.JPanel();
        productTitle2 = new javax.swing.JLabel();
        productImage2 = new javax.swing.JPanel();
        productTag2 = new javax.swing.JLabel();
        productPrice2 = new javax.swing.JLabel();
        addProductButton2 = new javax.swing.JButton();
        productTemplatePanel3 = new javax.swing.JPanel();
        productTitle3 = new javax.swing.JLabel();
        productImage3 = new javax.swing.JPanel();
        productTag3 = new javax.swing.JLabel();
        productPrice3 = new javax.swing.JLabel();
        addProductButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 960));
        setMinimumSize(new java.awt.Dimension(540, 960));

        jButton1.setText("(●__●)");

        favoriteButton.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        favoriteButton.setText("❤️");

        searchButton.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        searchButton.setText("🔎");

        searchField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(102, 102, 102));
        searchField.setText("Buscar");

        navBar.setBackground(new java.awt.Color(102, 102, 102));

        homeButton.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        homeButton.setText("🏠");

        whatToBuyWindowButton.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        whatToBuyWindowButton.setText("🗑");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        addProductsWindowButton.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        addProductsWindowButton.setText("➕");

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addProductsWindowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(whatToBuyWindowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whatToBuyWindowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProductsWindowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        productTemplatePanel.setBackground(new java.awt.Color(204, 204, 204));

        productTitle.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTitle.setText("Milk");

        Image.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout ImageLayout = new javax.swing.GroupLayout(Image);
        Image.setLayout(ImageLayout);
        ImageLayout.setHorizontalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ImageLayout.setVerticalGroup(
            ImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        productTag.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTag.setText("Comun");

        productPrice.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPrice.setText("2,99$");

        addProductButton.setText("Add");

        javax.swing.GroupLayout productTemplatePanelLayout = new javax.swing.GroupLayout(productTemplatePanel);
        productTemplatePanel.setLayout(productTemplatePanelLayout);
        productTemplatePanelLayout.setHorizontalGroup(
            productTemplatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productTemplatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(productTemplatePanelLayout.createSequentialGroup()
                        .addComponent(productTag, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productTemplatePanelLayout.setVerticalGroup(
            productTemplatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productTemplatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTag)
                    .addComponent(productPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        productTemplatePanel1.setBackground(new java.awt.Color(204, 204, 204));

        productTitle1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTitle1.setText("Crisps");

        productImage1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout productImage1Layout = new javax.swing.GroupLayout(productImage1);
        productImage1.setLayout(productImage1Layout);
        productImage1Layout.setHorizontalGroup(
            productImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productImage1Layout.setVerticalGroup(
            productImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        productTag1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTag1.setText("Emilio");

        productPrice1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productPrice1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPrice1.setText("2,49$");

        addProductButton1.setText("Add");

        javax.swing.GroupLayout productTemplatePanel1Layout = new javax.swing.GroupLayout(productTemplatePanel1);
        productTemplatePanel1.setLayout(productTemplatePanel1Layout);
        productTemplatePanel1Layout.setHorizontalGroup(
            productTemplatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productTemplatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(productTemplatePanel1Layout.createSequentialGroup()
                        .addComponent(productTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productTemplatePanel1Layout.setVerticalGroup(
            productTemplatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productTemplatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTag1)
                    .addComponent(productPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        productTemplatePanel2.setBackground(new java.awt.Color(204, 204, 204));

        productTitle2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTitle2.setText("Coke");

        productImage2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout productImage2Layout = new javax.swing.GroupLayout(productImage2);
        productImage2.setLayout(productImage2Layout);
        productImage2Layout.setHorizontalGroup(
            productImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productImage2Layout.setVerticalGroup(
            productImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        productTag2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTag2.setText("Pablo");

        productPrice2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productPrice2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPrice2.setText("4,99$");

        addProductButton2.setText("Add");

        javax.swing.GroupLayout productTemplatePanel2Layout = new javax.swing.GroupLayout(productTemplatePanel2);
        productTemplatePanel2.setLayout(productTemplatePanel2Layout);
        productTemplatePanel2Layout.setHorizontalGroup(
            productTemplatePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productTemplatePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(productTemplatePanel2Layout.createSequentialGroup()
                        .addComponent(productTag2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productTemplatePanel2Layout.setVerticalGroup(
            productTemplatePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productTemplatePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTag2)
                    .addComponent(productPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        productTemplatePanel3.setBackground(new java.awt.Color(204, 204, 204));

        productTitle3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTitle3.setText("Eggs");

        productImage3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout productImage3Layout = new javax.swing.GroupLayout(productImage3);
        productImage3.setLayout(productImage3Layout);
        productImage3Layout.setHorizontalGroup(
            productImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productImage3Layout.setVerticalGroup(
            productImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        productTag3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productTag3.setText("Comun");

        productPrice3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        productPrice3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        productPrice3.setText("3,45$");

        addProductButton3.setText("Add");

        javax.swing.GroupLayout productTemplatePanel3Layout = new javax.swing.GroupLayout(productTemplatePanel3);
        productTemplatePanel3.setLayout(productTemplatePanel3Layout);
        productTemplatePanel3Layout.setHorizontalGroup(
            productTemplatePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productTemplatePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProductButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(productTemplatePanel3Layout.createSequentialGroup()
                        .addComponent(productTag3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productPrice3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productTemplatePanel3Layout.setVerticalGroup(
            productTemplatePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTemplatePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productTemplatePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTag3)
                    .addComponent(productPrice3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProductButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainWindowPanelLayout = new javax.swing.GroupLayout(mainWindowPanel);
        mainWindowPanel.setLayout(mainWindowPanelLayout);
        mainWindowPanelLayout.setHorizontalGroup(
            mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainWindowPanelLayout.createSequentialGroup()
                        .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainWindowPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(favoriteButton))
                            .addComponent(searchField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainWindowPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productTemplatePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productTemplatePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productTemplatePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productTemplatePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        mainWindowPanelLayout.setVerticalGroup(
            mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWindowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(favoriteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(searchField))
                .addGap(18, 18, 18)
                .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productTemplatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productTemplatePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(mainWindowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productTemplatePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productTemplatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Image;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton addProductButton1;
    private javax.swing.JButton addProductButton2;
    private javax.swing.JButton addProductButton3;
    private javax.swing.JButton addProductsWindowButton;
    private javax.swing.JButton favoriteButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel mainWindowPanel;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel productImage1;
    private javax.swing.JPanel productImage2;
    private javax.swing.JPanel productImage3;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productPrice1;
    private javax.swing.JLabel productPrice2;
    private javax.swing.JLabel productPrice3;
    private javax.swing.JLabel productTag;
    private javax.swing.JLabel productTag1;
    private javax.swing.JLabel productTag2;
    private javax.swing.JLabel productTag3;
    private javax.swing.JPanel productTemplatePanel;
    private javax.swing.JPanel productTemplatePanel1;
    private javax.swing.JPanel productTemplatePanel2;
    private javax.swing.JPanel productTemplatePanel3;
    private javax.swing.JLabel productTitle;
    private javax.swing.JLabel productTitle1;
    private javax.swing.JLabel productTitle2;
    private javax.swing.JLabel productTitle3;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton whatToBuyWindowButton;
    // End of variables declaration//GEN-END:variables
}
